### PR TITLE
Split IE and Edge

### PR DESCRIPTION
**Pull request by danncoba**
Hey avct

I've split ie and edge detection. I would like for this to become official if you're interested

Please give me your opinion.

Regards.

### CODE REVIEW

**Comment by xavivars** [comment]
Hey @danncoba, thanks for these changes!

I'm maintaining a fork of uasurfer, where I've been merging some of the outsanding MRs from this repo, in case this is useful for you: https://github.com/xavivars/uasurfer

**Comment by danncoba** [comment]
Ok tnx

Ill be merging my changes there than.

If this is the place many updates id like to be a part of the updates if its possible, because i like ua surfer and would like to add to it

Regards

**Comment by xavivars** [comment]
@danncoba I already merged your changes there (and fixed some tests). I'm happy to move this to a more generic repo, and have more people contributing.

**Comment by danncoba** [comment]
I'll be adding code on a regular basis. 
We can play around with different repos, but the important thing is we have something stable to work on. @xavivars please let me know which repo do you finally decide on and we can start contributing
Regards

**Comment by xavivars** [comment]
@danncoba feel free to send MRs against https://github.com/xavivars/uasurfer

**Pull request closed without merging**
