### PR TITLE
Minor and patch versions for OS and Browser - v2

### PR DESCRIPTION
**Pull request by c2h5oh**
I rewrote this and in the process removed most of regexes (down to 1 from 10+) and refactored a couple of other things.

For Parse() number of allocations is down by 33%, allocated bytes up by 21% (to be expected - each version is now 3 ints, not 1), processing time is down by almost 18%.

```
name                  old time/op    new time/op    delta
AgentSurfer-8           5.31µs ± 1%    4.37µs ± 1%   -17.74%  (p=0.008 n=5+5)
EvalSystem-8            2.57µs ± 1%    2.49µs ± 2%    -3.05%  (p=0.008 n=5+5)
EvalBrowserName-8        526ns ± 1%     521ns ± 1%      ~     (p=0.175 n=5+5)
EvalBrowserVersion-8    1.24µs ± 1%    0.09µs ± 1%   -92.97%  (p=0.008 n=5+5)
EvalDevice-8             526ns ± 2%     517ns ± 2%      ~     (p=0.103 n=5+5)
ParseChromeMac-8        3.26µs ± 2%    2.54µs ± 1%   -21.97%  (p=0.008 n=5+5)
ParseChromeWin-8        2.90µs ± 0%    2.45µs ± 1%   -15.39%  (p=0.008 n=5+5)
ParseChromeAndroid-8    5.90µs ± 2%    5.44µs ± 1%    -7.87%  (p=0.008 n=5+5)
ParseSafariMac-8        3.54µs ± 0%    2.89µs ± 0%   -18.32%  (p=0.016 n=4+5)
ParseSafariiPad-8       4.30µs ± 1%    3.18µs ± 1%   -26.12%  (p=0.008 n=5+5)

name                  old alloc/op   new alloc/op   delta
AgentSurfer-8             265B ± 0%      320B ± 0%   +20.75%  (p=0.008 n=5+5)
EvalSystem-8             0.00B          0.00B           ~     (all equal)
EvalBrowserName-8        0.00B          0.00B           ~     (all equal)
EvalBrowserVersion-8     15.0B ± 0%      0.0B       -100.00%  (p=0.008 n=5+5)
EvalDevice-8             0.00B          0.00B           ~     (all equal)
ParseChromeMac-8          288B ± 0%      336B ± 0%   +16.67%  (p=0.008 n=5+5)
ParseChromeWin-8          240B ± 0%      304B ± 0%   +26.67%  (p=0.008 n=5+5)
ParseChromeAndroid-8      320B ± 0%      368B ± 0%   +15.00%  (p=0.008 n=5+5)
ParseSafariMac-8          288B ± 0%      336B ± 0%   +16.67%  (p=0.008 n=5+5)
ParseSafariiPad-8         288B ± 0%      336B ± 0%   +16.67%  (p=0.008 n=5+5)

name                  old allocs/op  new allocs/op  delta
AgentSurfer-8             3.00 ± 0%      2.00 ± 0%   -33.33%  (p=0.008 n=5+5)
EvalSystem-8              0.00           0.00           ~     (all equal)
EvalBrowserName-8         0.00           0.00           ~     (all equal)
EvalBrowserVersion-8      0.00           0.00           ~     (all equal)
EvalDevice-8              0.00           0.00           ~     (all equal)
ParseChromeMac-8          4.00 ± 0%      3.00 ± 0%   -25.00%  (p=0.008 n=5+5)
ParseChromeWin-8          3.00 ± 0%      3.00 ± 0%      ~     (all equal)
ParseChromeAndroid-8      4.00 ± 0%      3.00 ± 0%   -25.00%  (p=0.008 n=5+5)
ParseSafariMac-8          4.00 ± 0%      3.00 ± 0%   -25.00%  (p=0.008 n=5+5)
ParseSafariiPad-8         4.00 ± 0%      3.00 ± 0%   -25.00%  (p=0.008 n=5+5)
```

### CODE REVIEW

**Comment by c2h5oh** [comment]
@jacobpierce this one is faster than current master and passes all the tests, but because I got rid of most regexes I would highly recommend it is tested against actual data to verify accuracy has not suffered.

**Comment by c2h5oh** [comment]
Aaand bump (sorry - but this seems to work :P)

**Comment by c2h5oh** [comment]
and one more :-)

**Comment by c2h5oh** [comment]
Bumptipy-bump. If this is becoming more annoying than helpful just say a word :-)

**Comment by scritchley** [comment]
Hi @c2h5oh, I'm going to pick up on this. The improvements look good, so we are going to get this merged. Thanks for contributing!

**Comment by scritchley** [comment]
One follow up we are planning is to add some tooling to this repo to allow us to compare results between versions. Aiming to follow up with that in the next couple of weeks. I'll make sure to accompany that with a decent (~100K) test dataset.

**Comment by c2h5oh** [comment]
The larger the dataset the better - I'm exploring some ideas using Thompson NFA and radix tries and it would be great to be able to test them on a larger dataset.

**Pull request merged**
